const Currencies = {
  "AUD": "Australian Dollar",
  "BRL": "Brazilian Real",
  "GBP": "British Pound",
  "BGN": "Bulgarian Lev",
  "CAD": "Canadian Dollar",
  "CZK": "Czech Koruna",
  "DKK": "Danish Krone",
  "EUR": "Euro",
  "HKD": "Hong Kong Dollar",
  "HUF": "Hungarian Forint",
  "ILS": "Israeli New Sheqel",
  "JPY": "Japanese Yen",
  "MYR": "Malaysian Ringgit",
  "MXN": "Mexican Peso",
  "TWD": "New Taiwan Dollar",
  "NZD": "New Zealand Dollar",
  "NOK": "Norwegian Krone",
  "PHP": "Philippine Peso",
  "PLN": "Polish Złoty",
  "RON": "Romania Leu",
  "RUB": "Russian Ruble",
  "SGD": "Singapore Dollar",
  "SEK": "Swedish Krona",
  "CHF": "Swiss Franc",
  "THB": "Thai Baht",
  "USD": "United States Dollar"
};

export default Currencies;
